/*******************************************************************************************************************************************/

// Loading Partition users for R1 - Avinash Rao - April 2005
// Loads the missing supervisors file generated by CATMissingSuper.java.

/*******************************************************************************************************************************************/

package config.java.schedule;

import java.util.Map;

import ariba.base.core.Base;
import ariba.base.core.Partition;
import ariba.util.core.MapUtil;
import ariba.util.messaging.CallCenter;
import ariba.util.scheduler.ScheduledTask;
import ariba.util.scheduler.ScheduledTaskException;

public class LoadMissingSuper extends ScheduledTask
{

    public void run() throws ScheduledTaskException
    {
		ariba.base.core.Log.customer.debug("Beginning Super load program .....");
		Partition partition = Base.getSession().getPartition();

        try
        {
       		CallCenter callCenter = CallCenter.defaultCenter();
    		Map userInfo = MapUtil.map();
            Map userData = MapUtil.map();

			userInfo.put("Partition", partition.getName());
			userData.put("EventSource", "PasswordAdapter1");
            userData.put("Filename", "CATMissingSuper.csv");

			callCenter.call("CATSuperPull",userData,userInfo);
			ariba.base.core.Log.customer.debug("called super");
			Base.getSession().transactionCommit();
			ariba.base.core.Log.customer.debug("Ending integration and exiting");

		} // end of try

		catch (Exception e)
		{
			ariba.base.core.Log.customer.debug(e.toString());
			return;
		}
    }

    public LoadMissingSuper()
    {
    }

}

/*******************************************************************************************************************************************/
