/*******************************************************************************************************************************************/

// Loading Partition users for R1 - Avinash Rao - April 2005
// Loads the exclusions csv file generated by the UserLoad.java program.

/*******************************************************************************************************************************************/

package config.java.schedule;

import java.util.Map;

import ariba.base.core.Base;
import ariba.base.core.Partition;
import ariba.util.core.MapUtil;
import ariba.util.messaging.CallCenter;
import ariba.util.scheduler.ScheduledTask;
import ariba.util.scheduler.ScheduledTaskException;

public class LoadExclusions extends ScheduledTask
{

    public void run() throws ScheduledTaskException
    {
		ariba.base.core.Log.customer.debug("Beginning Exclusions load program .....");
		Partition partition = Base.getSession().getPartition();

        try
        {
       		CallCenter callCenter = CallCenter.defaultCenter();
    		Map userInfo = MapUtil.map();
            Map userData2 = MapUtil.map();

			userInfo.put("Partition", partition.getName());
			userData2.put("EventSource", "PasswordAdapter1");
            userData2.put("Filename", "Exclusions.csv");

			callCenter.call("CATExclusionsPull",userData2,userInfo);
			ariba.base.core.Log.customer.debug("called exclusions");
			Base.getSession().transactionCommit();
			ariba.base.core.Log.customer.debug("Ending integration and exiting");

		} // end of try

		catch (Exception e)
		{
			ariba.base.core.Log.customer.debug(e.toString());
			return;
		}
    }

    public LoadExclusions()
    {
    }

}

/*******************************************************************************************************************************************/
